spring:
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  sql:
    init:
      mode: always
      platform: postgres

  datasource:
    password: 123_Stella
    url: ${web_service_db_url}
    username: postgres

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  banner:
    location: classpath:banner.txt
    
#==========================================================
#= PriceArt Web Service - Versione Sicurezza JWT
#==========================================================
server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: 123_Stella

springdoc:
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  api-docs:
    enabled: true
  packages-to-scan: com.xantrix.webapp.controllers

# ==============================================================
# = Livello Log di Sicurezza
# ==============================================================
logging:
  file:
    path: ./logs
    name: ArtSrv.log
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    #console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
  level:
    root: WARN
    # livello di log specifico per package
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.hibernate: INFO
    org.springframework.web: INFO
    com.xantrix.webapp.controllers: INFO
  logback:
    rollingpolicy:
      max-file-size: 1MB

# ==============================================================
# = Parametri Sicurezza OAUTH2 con KeyCloack
# ==============================================================
keycloak:
  auth-server-url: http://${keycloak_host}:${keycloak_port}/
  realm: ${realm}
  resource: Articoli-Web-Service
  public-client: true
  enabled: true
  ssl-required: external
  confidential-port: 0

# ==============================================================
# = Actuator parameters
# ==============================================================
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints: #per esporre tutti gli endpoint
    web:
      exposure:
        include: health,info,metrics,customInfo

# ==============================================================
# = Actuator info
# ==============================================================
info:
  assistenza:
    nome: "Nicolò Rossi"
    mail: "nicolo.rossi@biters.it"
    sito: "biters.it"
  nome:
    nome-app: "Articoli Web Service - Versione OAuth 2.0"
